Feat/refactor address nft tokens
EthVM/EthVM pull request #1020
Opened 2022-07-28 14:14 UTC by Abdulqudus001

2022-08-01 23:00 UTC, olgakup requested changes

2022-08-01 23:00 UTC, olgakup commented on v2/src/apollo/opensea/OpenSeaClient.ts
> +const transformAddressNFTcontracts = (data: any) => {
it would be nice if we can actually use interface here instead of any

2022-08-02 19:34 UTC, Abdulqudus001 commented on v2/src/modules/address/components/SingleAddressNft.vue
> +<template>
Rename to `AddressContractNfts`

2022-08-09 19:52 UTC, olgakup approved these changes

2022-08-09 19:53 UTC, merged